# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 09:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
