# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='username',
            field=models.CharField(default='demon', max_length=20, unique=True),
        ),
    ]
